version: '3.5'

services:
  db_haircutbookingsystem:
    container_name: db_haircutbookingsystem
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image: postgres:14.5