version: '3.5'

services:
  db_haircutbookingsystem:
    container_name: db_haircutbookingsystem
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_USER=${user}
    image: postgres:14.5